### ISSUE TITLE
Unify Verboice's "callers" metric with Pollit's "numbers_by_country_code"

### ISSUE THREAD

**Issue by nditada** [instedd/telemetry_rails#100]
They seem to be pretty much equivalent, would be nice to be able to do queries cross-app.

**Comment by nditada** [comment]
Also, we might be able to unify Remindem's "phone_numbers".

**Comment by bcardiff** [comment]
Pollit ready waiting for deployment.

**Comment by bcardiff** [comment]
Remindem ready waiting for deployment

**Comment by bcardiff** [comment]
Nuntium also has de metric. It will be unified.
