### ISSUE TITLE
Pollit missing reports?

### ISSUE THREAD

**Issue by nditada** [instedd/telemetry_rails#101]
According to the log, Pollit reported events on Feb 18, but I cannot find any events after Feb 11.

**Comment by juanedi** [comment]
Just checked and there seems to be data from that report.

If pollit reported on Feb 18 then that information must be from the period [beginning: Feb11, end: Feb18), so any plot defined using the `beginning` field as timestamp will look like there is no data from Feb18.

**Comment by nditada** [comment]
Ok, closing for now. Tomorrow or the day after it should become visible then.
