### ISSUE TITLE
Number of Callers is not reported correctly

### ISSUE THREAD

**Issue by mmuller** [instedd/telemetry_rails#106]
Preconditions:
In Verboice there is 1 caller where project_id:560

Reproduce steps:
Go to Discover tab in telemetry-stg
Query 'application:verboice AND metric:callers AND key.project_id:560'

Obtained: 
3 callers are reported in Telemetry
Number of Callers is not reported correctly

![screen shot 2016-03-01 at 10 37 25 am](https://cloud.githubusercontent.com/assets/518152/13428526/cd226356-df99-11e5-8b4f-a5695fd6b543.png)
![screen shot 2016-03-01 at 10 36 17 am](https://cloud.githubusercontent.com/assets/518152/13428527/cd23d402-df99-11e5-8c94-f860dbce02ce.png)

**Comment by romeroadrian** [comment]
The metrics refers to contacts in the address book (which is this case is actually 3).
