### ISSUE TITLE
Telemetry Acknowledgment a bit alarmist

### ISSUE THREAD

**Issue by edjez** [instedd/telemetry_rails#107]
Expected: 
"FYI, this server is reporting anonymous stats and errors to InSTEDD telemetry. Thank you for helping us improve product reliability."

Current: 
something alarmist in all caps like:
"AAAAGH THIS IS RUNNING TEH TELEMETREE."

**Comment by spalladino** [comment]
This is how it looks today. @jkicillof ideas?

![screen shot 2016-11-02 at 1 39 33 pm](https://cloud.githubusercontent.com/assets/429604/19937935/d5d665f4-a101-11e6-893e-864f95b59ec8.png)

**Comment by waj** [comment]
Keep in mind this can be seen by any user entering the site. The first one who act on it wins with the configuration.

**Comment by spalladino** [comment]
@jkicillof suggested removing the WARNING banner altogether, and always redirect the first user to access the site to the configuration page; and add a short explanation on what Telemetry is there. WDYT?
