### ISSUE TITLE
Duplicate Resmap instances

### ISSUE THREAD

**Issue by nditada** [instedd/telemetry_rails#108]
There are four instances of ResourceMap @ 190.111.238.39 reporting data.

**Comment by juanedi** [comment]
All of these installations have different UUIDs, and I can't think of a situation in which the telemetry agent regenerates its UUID.

Also, they registered within a 4 day period and never reported any information, nor provided any contact email. Maybe someone was trying to set up a new Resmap installation and reset the database multiple times while doing so?

**Comment by nditada** [comment]
The IP is from Argentina. San Isidro to be more precise :-). I'll delete those servers.
